<?php

namespace AutomateWoo;

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * @class Settings_Tab_General
 */
class Settings_Tab_General extends Admin_Settings_Tab_Abstract {

	function __construct() {
		$this->id = 'general';
		$this->name = __( 'General', 'automatewoo' );
	}


	function load_settings() {

		$this->section_start( 'general' );

		$this->add_setting( 'session_tracking_enabled', [
			'type' => 'checkbox',
			'title' => __( 'Enable session tracking', 'automatewoo' ),
			'desc' => __( "Use cookies to track customers who aren't logged in. This is required for tracking carts belonging to guest customers. This is also used by the Refer A Friend add-on to reduce fraud.", 'automatewoo' ),
			'autoload' => true
		]);

		$this->add_setting( 'conversion_window', [
			'title' => __( 'Conversion tracking window', 'automatewoo' ),
			'desc_tip' => __( 'Sets the number of days after a workflow runs that a new order can be considered a conversion. Default value is 14.', 'automatewoo' ),
			'type' => 'number',
		]);

		$this->add_setting( 'clean_expired_coupons', [
			'title' => __( 'Automatically delete expired coupons', 'automatewoo' ),
			'desc' => __( 'Coupons generated by AutomateWoo will be deleted 14 days after they expire.', 'automatewoo' ),
			'type' => 'checkbox'
		]);

		$this->section_end( 'general' );

		$this->section_start( 'email', __( 'Email sender options', 'automatewoo' ) );

		$this->add_setting( 'email_from_name', [
			'title' => __( 'From name', 'automatewoo' ),
			'desc_tip' => __( 'How the sender name appears in outgoing AutomateWoo emails. If blank the WooCommerce sender name will be used.', 'automatewoo' ),
			'type' => 'text',
			'placeholder' => get_option( 'woocommerce_email_from_name' )
		]);


		$this->add_setting( 'email_from_address', [
			'title' => __( 'From email', 'automatewoo' ),
			'desc_tip' => __( 'How the sender email appears in outgoing AutomateWoo emails. If blank the WooCommerce sender email will be used.', 'automatewoo' ),
			'type' => 'text',
			'placeholder' => get_option( 'woocommerce_email_from_address' )
		]);

		$this->section_end( 'email' );
	}

}

return new Settings_Tab_General();
