<?php
/**
 * WARNING! DO NOT EDIT THIS FILE DIRECTLY!
 *
 * FOR CUSTOM CSS USE THE PLUGIN THEME OPTIONS->CUSTOM CSS PANEL.
 */

/* Prevent direct access */
defined('ABSPATH') or die("You can't access this file directly.");
?>

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.vertical,
    <?php echo $asp_res_ids2; ?>.vertical,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.vertical {
    padding: 4px;
    background: <?php echo $style['resultsbackground']; ?>;
    border-radius: 3px;
    <?php echo $style['resultsborder']; ?>
    <?php echo $style['resultshadow']; ?>
    visibility: hidden;
    display: none;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.vertical .results,
    <?php echo $asp_res_ids2; ?>.vertical .results,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.vertical .results {
    max-height: <?php echo $style['v_res_max_height']; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.vertical .item .asp_content h3,
    <?php echo $asp_res_ids2; ?>.vertical .item .asp_content h3,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.vertical .item .asp_content h3 {
    display: inline;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.vertical .results .item .asp_content,
    <?php echo $asp_res_ids2; ?>.vertical .results .item .asp_content,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.vertical .results .item .asp_content {
    overflow: hidden;
    width: auto;
    height: <?php echo $style['resultitemheight']; ?>;
    background: transparent;
    margin: 0;
    padding: 0 10px;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.vertical .results .item .asp_image,
    <?php echo $asp_res_ids2; ?>.vertical .results .item .asp_image,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.vertical .results .item .asp_image {
    width: <?php echo $style['image_width']; ?>px;
    height: <?php echo $style['image_height']; ?>px;
    margin: 2px 8px 0px 0;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?>.vertical .results .asp_spacer,
    <?php echo $asp_res_ids2; ?>.vertical .results .asp_spacer,
<?php endif; ?>
<?php echo $asp_res_ids; ?>.vertical .results .asp_spacer {
    background: <?php echo $style['spacercolor']; ?>;
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .mCSBap_scrollTools .mCSBap_dragger .mCSBap_dragger_bar,
    <?php echo $asp_res_ids2; ?> .mCSBap_scrollTools .mCSBap_dragger .mCSBap_dragger_bar,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .mCSBap_scrollTools .mCSBap_dragger .mCSBap_dragger_bar {
    background:#fff; /* rgba fallback */
    background:rgba(<?php echo wpdreams_hex2rgb($style['overflowcolor']); ?>,0.9);
}

<?php if ($use_compatibility == true): ?>
    <?php echo $asp_res_ids1; ?> .mCSBap_scrollTools .mCSBap_dragger:hover .mCSBap_dragger_bar,
    <?php echo $asp_res_ids2; ?> .mCSBap_scrollTools .mCSBap_dragger:hover .mCSBap_dragger_bar,
<?php endif; ?>
<?php echo $asp_res_ids; ?> .mCSBap_scrollTools .mCSBap_dragger:hover .mCSBap_dragger_bar {
    background:rgba(<?php echo wpdreams_hex2rgb($style['overflowcolor']); ?>,0.95);
}

<?php echo $asp_res_ids; ?> .mCSBap_scrollTools .mCSBap_dragger:active .mCSBap_dragger_bar,
<?php echo $asp_res_ids; ?> .mCSBap_scrollTools .mCSBap_dragger.mCSBap_dragger_onDrag .mCSBap_dragger_bar{
    background:rgba(<?php echo wpdreams_hex2rgb($style['overflowcolor']); ?>,1);
}

<?php echo $asp_res_ids; ?>.horizontal .mCSBap_scrollTools .mCSBap_dragger .mCSBap_dragger_bar{
    background:#fff; /* rgba fallback */
    background:<?php echo $style['hoverflowcolor']; ?>;
    opacity: 0.9;
}
<?php echo $asp_res_ids; ?>.horizontal .mCSBap_scrollTools .mCSBap_dragger:hover .mCSBap_dragger_bar{
    background:<?php echo $style['hoverflowcolor']; ?>;
    opacity: 0.95;
}

<?php echo $asp_res_ids; ?>.horizontal .mCSBap_scrollTools .mCSBap_dragger:active .mCSBap_dragger_bar,
<?php echo $asp_res_ids; ?>.horizontal .mCSBap_scrollTools .mCSBap_dragger.mCSBap_dragger_onDrag .mCSBap_dragger_bar{
    background: <?php echo $style['hoverflowcolor']; ?>;
}

<?php echo $asp_res_ids; ?> .mCSBap_scrollTools .mCSBap_buttonDown {
    position: relative;
    margin: -16px 0px 0 3px;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 6px 5px 0 5px;
    border-color: <?php echo $style['arrowcolor']; ?> transparent transparent transparent;
}

<?php echo $asp_res_ids; ?> .mCSBap_scrollTools .mCSBap_buttonUp {
    position: relative;
    margin: -8px 0px 0 3px;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 0 5px 6px 5px;
    border-color: transparent transparent <?php echo $style['arrowcolor']; ?> transparent;
}